# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import image_transfer_pb2 as image__transfer__pb2


class ImageTransferStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetGenerateImage = channel.unary_unary(
        '/services.ImageTransfer/GetGenerateImage',
        request_serializer=image__transfer__pb2.Image.SerializeToString,
        response_deserializer=image__transfer__pb2.Images.FromString,
        )
    self.RandomizeNoise = channel.unary_unary(
        '/services.ImageTransfer/RandomizeNoise',
        request_serializer=image__transfer__pb2.Empty.SerializeToString,
        response_deserializer=image__transfer__pb2.Empty.FromString,
        )


class ImageTransferServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetGenerateImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RandomizeNoise(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageTransferServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetGenerateImage': grpc.unary_unary_rpc_method_handler(
          servicer.GetGenerateImage,
          request_deserializer=image__transfer__pb2.Image.FromString,
          response_serializer=image__transfer__pb2.Images.SerializeToString,
      ),
      'RandomizeNoise': grpc.unary_unary_rpc_method_handler(
          servicer.RandomizeNoise,
          request_deserializer=image__transfer__pb2.Empty.FromString,
          response_serializer=image__transfer__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'services.ImageTransfer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
